name: financial-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - duckdb
  - pyarrow
  
  - pip:
    - fastparquet
    - gcsfs
    - google-cloud-storage
    - pandas
    - pandas-ta
    - plotly
    - pytest
    - pytest-mock
    - python-dotenv
    - numpy
    - requests
    - streamlit
    - urllib3
    - websocket-client